spring:
  profiles:
    active: development
    
--------------------------------

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SweetChilliSoftware/Haulage-Management-System/configuration-files/
        health:
          
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: config-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
